---
- file: path=/jupyter/admin/admin_tools state=directory
- file: path=/jupyter/admin/tools state=directory
- file: path=/jupyter/admin/textbook state=directory
- file: path=/jupyter/admin/info state=directory
- file: path=/home/{{default_user}}/manage-tools state=directory

- copy: src=admin-tools dest=/home/{{default_user}}/manage-tools/
- copy: src=tools dest=/home/{{default_user}}/manage-tools/
- copy: src=common dest=/home/{{default_user}}/manage-tools/

- shell: chdir=/home/{{default_user}}/ cp manage-tools/admin-tools/* /jupyter/admin/admin_tools/
- shell: chdir=/home/{{default_user}}/ cp manage-tools/tools/* /jupyter/admin/tools/
- shell: chdir=/home/{{default_user}}/ cp manage-tools/common/* /jupyter/admin/admin_tools/
- shell: chdir=/home/{{default_user}}/ cp manage-tools/common/* /jupyter/admin/tools/

- shell: chmod a+x /jupyter/admin/tools/notebook-diff /jupyter/admin/admin_tools/notebook-diff \
         /jupyter/admin/admin_tools/collect-answer
